name: cookie-classify
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - pip
  - selenium
  - firefox
  - geckodriver
  - pip:
    - selenium-wire
    - tldextract
    - Pillow
    - mypy
    - types-requests